theme: jekyll-theme-minimal
title: Covid-19 Thane Dashboard
description: An unoffical Covid-19 Dashboard for Thane District.
logo: https://github.com/covid19-thane/covid19-thane.github.io/blob/master/images/logo.png?raw=true
show_downloads: False
