theme: jekyll-theme-minimal
title: Covid-19 Thane Dashboard
description: An unoffical Covid-19 Dashboard for Thane District.
logo: https://avatars2.githubusercontent.com/u/37355997?s=460&u=7512e6bab341d71e91d8aff2d40008268a416fb2&v=4
show_downloads: False
